In [4]:
# Dependencies
import pandas as pd

In [12]:
# Read data set
pd.read_csv(".//Resources//lol_dataset.csv")

,Team,Player,Opponent,Position,Champion,Kills,Deaths,Assists,Creep Score,Gold Earned,Champion Damage Share,Kill Participation,Wards Placed,Wards Destroyed,Ward Interactions,Dragons For,Dragons Against,Barons For,Barons Against,Result
0,UOL,Boss,GS,Top,Camille,4,5,3,188,11107,0.17,0.78,8,8,16,0,4,0,1,L
1,GS,Crazy,UOL,Top,Gwen,3,1,9,217,12201,0.20,0.52,10,7,17,4,0,1,0,W
2,UOL,Ahahacik,GS,Jungle,Trundle,2,4,5,156,9048,0.15,0.78,8,14,22,0,4,0,1,L
3,GS,Mojito,UOL,Jungle,Talon,5,4,10,194,11234,0.23,0.65,12,8,20,4,0,1,0,W
4,UOL,Nomanz,GS,Mid,Leblanc,1,3,4,216,9245,0.29,0.56,6,9,15,0,4,0,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,BYG,Maoan,UOL,Mid,Ryze,4,4,2,356,15558,0.23,0.32,24,6,30,4,1,1,1,W
216,UOL,Argonavt,BYG,Adc,Senna,1,3,9,58,9554,0.16,0.71,35,16,51,1,4,1,1,L
217,BYG,Doggo,UOL,Adc,Draven,10,2,4,353,20546,0.38,0.74,15,5,20,4,1,1,1,W
218,UOL,Santas,BYG,Support,Wukong,0,4,7,200,10354,0.11,0.50,16,8,24,1,4,1,1,L
219,BYG,Kino,UOL,Support,Rakan,0,5,9,41,9304,0.06,0.47,49,15,64,4,1,1,1,W

In [8]:
df = pd.read_csv(".//Resources//lol_dataset.csv")

In [13]:
df["Player"].value_counts()

Blaber        5
Yutapon       5
Argonavt      5
Evi           5
Maoan         5
Husha         5
Fudge         5
Steal         5
Doggo         5
Zven          5
Aria          5
Kino          5
Perkz         5
Ahahacik      5
Nomanz        5
Santas        5
Gaeng         5
Boss          5
Crazy         4
Tally         4
Tarzan        4
Willer        4
Vizicsacsi    4
Ackerman      4
Titan         4
Guigo         4
Violet        4
Ale           4
Deft          4
Buggax        4
Icon          4
Solidsnake    4
Light         4
Bolulu        4
Jojo          4
Chovy         4
Morgan        4
Iwandy        4
Whitelotus    4
Cody          4
Aladoric      4
Vulcan        4
Mojito        4
Liang         4
Alive         4
Grevthar      4
Aegis         4
Babip         3
Vsta          3
Zergsting     3
Bulcan        1
Zersting      1
Leona         1
Pk            1
Bapip         1
Name: Player, dtype: int64